Update deploy-db.yaml

diff --git a/.github/workflows/deploy-db.yaml b/.github/workflows/deploy-db.yaml
--- a/.github/workflows/deploy-db.yaml
+++ b/.github/workflows/deploy-db.yaml
@@ -23,8 +23,15 @@ jobs:
 
     - name: run the bash script to install delta kusto CLI
       run: |
+      
+        # Fails if one of the command fails in the script
+        set -e
+        clientVersion=$(curl https://delta-kusto.azurefd.net/clientVersion/unique?fromClientVersion=0)
+        # Display the version on console
+        echo "Client Version:  $clientVersion"
+        wget https://github.com/microsoft/delta-kusto/releases/download/$clientVersion/delta-kusto-linux.tar.gz
 
-        wget https://github.com/microsoft/delta-kusto/releases/download/0.6.0.85/delta-kusto-linux.tar.gz
+        # wget https://github.com/microsoft/delta-kusto/releases/download/0.6.0.85/delta-kusto-linux.tar.gz
         tar --extract --file delta-kusto-linux.tar.gz 
         sudo cp delta-kusto /bin 
     
